name: CI-master

on:
  push:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Pull latest code
        uses: actions/checkout@v3
        with:
          ref: master

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Install Basement
        run: |
          pushd src
          npm install

      - name: Build
        run: |
          npm run build
          rm -rf ../static
          cp -r ./build/static/ ../static
          popd

      - name: Push
        run: |
          git add static
          git commit -m 'CI push'
          git push origin master
