name: CI-master

on:
  push:
    branches: [master]
#    paths:
#      - 'src/**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Pull latest code
        uses: actions/checkout@v3
        with:
          ref: master

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Install Basement & Build & Copy
        run: |
          cd src
          npm install
          npm run build
          rm -rf ../static
          cp -r ./build/static/ ../static

      - name: Push
        script:
          - git config --global user.email "CI push"
          - git config --global user.name "CI push"
          - git add -A
          - if [ $? -eq 0 ]; then
            - git commit -m 'CI push'
            - git push origin master
          - else
            -   echo "Skipping commit step due to empty add."  
          - fi
